config/routes.rb
Rails.application.routes.draw do
  resources :movies do
    resources :votes, only: [ :create ]
    delete "votes" => "votes#destroy"
  end

  get "login" => "sessions#new", as: :login
  post "login" => "sessions#create", as: :create_session
  delete "logout" => "sessions#destroy", as: :logout
  get "sign-up" => "users#new", as: :signup
  post "sign-up" => "users#create", as: :create_user

  resources :users, only: [ :create ]

  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :movies, dependent: :nullify
  has_many :votes, dependent: :nullify, class_name: "Movie::Vote"
  has_many :likes, -> { where(vote_type: :like) }, class_name: "Movie::Vote"
  has_many :dislikes, -> { where(vote_type: :dislike) }, class_name: "Movie::Vote"

  normalizes :email_address, with: ->(e) { e.strip.downcase }
  validates :email_address, format: URI::MailTo::EMAIL_REGEXP
  validates :email_address, uniqueness: true
  validates :email_address, length: { maximum: 100 }

  validates :password, presence: true, length: { minimum: 8 }
  validates :password_confirmation, presence: true, comparison: { equal_to: :password }

  validates :password_digest, presence: true

  validates :username, presence: true, uniqueness: true
  validates :username, length: { minimum: 3, maximum: 50 }

  validates_associated :votes

  def like(movie)
    return if movie.user == self

    if vote = votes.find_by(movie: movie)
      vote.update(vote_type: "like") unless vote.vote_type == "like"
      vote
    else
      votes.create(movie: movie, vote_type: "like")
    end
  end

  def dislike(movie)
    return if movie.user == self

    if vote = votes.find_by(movie: movie)
      vote.update(vote_type: "dislike") unless vote.vote_type == "dislike"
      vote
    else
      votes.create(movie: movie, vote_type: "dislike")
    end
  end

  def likes?(movie)
    likes.find_by(movie: movie).present?
  end

  def dislikes?(movie)
    dislikes.find_by(movie: movie).present?
  end

  def get_vote(movie)
    votes.find_by(movie_id: movie.id)
  end

  def has_submitted?(movie)
    movies.exists?(movie.id)
  end
end

app/models/user/vote.rb
class User::Vote < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :movie, uniqueness: { scope: :user, message: "can not vote more than once for a specific movie" }
  validates :vote_type, inclusion: { in: %w[like dislike] }
  validate :validate_not_own_submission

  def validate_not_own_submission
    errors.add :user, "User can not vote for movies they have submitted themselves" if movie.user.id == user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      start_new_session_for @user
      redirect_to after_authentication_url, notice: "Account created successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email_address, :password, :password_confirmation, :username)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/new.html.erb
<div class="form">
  <div class="welcome">
    <h1>Sign-up</h1>
    <p>Welcome! Please enter your email address and password to sign up.</p>
  </div>

  <%= tag.div(flash[:alert], style: "color:red") if flash[:alert] %>

  <%= form_with url: users_path, scope: :user, class: 'form' do |form| %>
    <div class="form-input">
        <%= form.label :username, "Username " %>
        <%= form.text_field :username, required: true, autofocus: true, placeholder: "Enter your username", value: params[:email_address] %>
    </div>

    <div class="form-input">
        <%= form.label :email_address, "Email" %>
        <%= form.email_field :email_address, required: true,  placeholder: "Enter your email address", value: params[:email_address] %>
    </div>

    <div class="form-input">
        <%= form.label :password, "Password" %>
        <%= form.password_field :password, required: true, placeholder: "Enter your password", maxlength: 72 %>
    </div>

    <div class="form-input">
        <%= form.label :password_confirmation, "Re-type password" %>
        <%= form.password_field :password_confirmation, required: true, placeholder: "Confirm password", maxlength: 72 %>
    </div>

    <%= form.submit "Sign up", class: "submit-form" %>
  <% end %>

  <div class="links">
    <%= link_to "Already have an account?", login_path %>
  </div>
</div>